### ISSUE TITLE
nomad/consul ip lookup with eth0 fails outside of AWS

### ISSUE THREAD

**Issue by ketzacoatl** [fpco/fpco-salt-formula#103]
```
[ERROR   ] Rendering exception occurred: Jinja variable 'dict object' has no attribute 'eth0'
[DEBUG   ] Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 2388, in managed
    **kwargs
  File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 3933, in get_managed
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 167, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 436, in render_jinja_tmpl
    buf=tmplstr)
SaltRenderError: Jinja variable 'dict object' has no attribute 'eth0'
[ERROR   ] Unable to manage file: Jinja variable 'dict object' has no attribute 'eth0'
```

**Comment by ketzacoatl** [comment]
#107 is a duplicate..
