### ISSUE TITLE
eth0 assumption is bad for vagrant

### ISSUE THREAD

**Issue by ketzacoatl** [fpco/fpco-salt-formula#123]
The formula was originally written for AWS hosts, and when looking up IPs and network interfaces, we assumed `eth0`. Vagrant uses a different name for the network interfaces, and our consul/nomad/etc formula (`grep` for `eth0`, though it looks like only `nomad.service` and `consul.ext_pillar`) need this assumption updated.

```
    default: [ERROR   ] Rendering exception occurred
    default: Traceback (most recent call last):
    default:   File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 169, in render_tmpl
    default:     output = render_str(tmplstr, context, tmplpath)
    default:   File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 390, in render_jinja_tmpl
    default:     buf=tmplstr)
    default: SaltRenderError: Jinja variable 'dict object' has no attribute 'eth0'
    default: [CRITICAL] Rendering SLS 'base:consul.ext_pillar.enable' failed: Jinja variable 'dict object' has no attribute 'eth0'
    default: [ERROR   ] Template was specified incorrectly: False
    default: [ERROR   ] Template was specified incorrectly: False
    default: [ERROR   ] Rendering exception occurred
    default: Traceback (most recent call last):
    default:   File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 169, in render_tmpl
    default:     output = render_str(tmplstr, context, tmplpath)
    default:   File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 390, in render_jinja_tmpl
    default:     buf=tmplstr)
    default: SaltRenderError: Jinja variable 'dict object' has no attribute 'eth0'
    default: [CRITICAL] Rendering SLS 'base:nomad.service' failed: Jinja variable 'dict object' has no attribute 'eth0'
    default: local:
    default:     Data failed to compile:
    default: ----------
    default:     Rendering SLS 'base:consul.ext_pillar.enable' failed: Jinja variable 'dict object' has no attribute 'eth0'
    default: ----------
    default:     Rendering SLS 'base:nomad.service' failed: Jinja variable 'dict object' has no attribute 'eth0'
```

**Comment by ketzacoatl** [comment]
once you have the vagrant VM running, run `salt-call --local state.sls nomad.service` to see this failure.

**Comment by lpaulmp** [comment]
This solution could be applied in the future but for now set `net_if:` in the pillar is the simplest fix.
```
# files consul_check_agent.sls  / service.sls
{%- if  grains.virtual == 'VirtualBox' %} 
{%- set interface_name = 'enp0s3' %} 
{%- else %} 
{%- set interface_name = 'eth0' %}
{%- endif %}
{%- set service_ip = salt['grains.get']('ip4_interfaces')[interface_name][0] %} 
```

**Comment by ketzacoatl** [comment]
This is resolved, great work @lpaulmp!
